### ISSUE TITLE
First time setup improvements

### ISSUE THREAD

**Issue by Leblayd** [Nitwel/Immersive-Home#103]
I am currently in the process of setting it up (and I'm stuck), so I decided to write down my struggles.

1. The instructions should be in the headset.
2. If not in the headset, they should be under a _large_ button on the _website_. Not an easy-to-miss link on the github page.
3. It should very clearly warn the user to "open Home Assistant dashboard _on the quest_ or be prepared to copy the string from the device you opened it on, unto the Quest" or similar. (And preferably update the image to show the Quest version of HASS, too.)
4. Make the paste button way more prominent. I didn't notice it before I read the instructions on the site, and I started typing it manually, having given up hope for copy-pasting it.
5. When typing on the keyboard, sometimes it gets stuck and thinks I want to move the UI (without touching the grips). But only when I am hovering over one of the keys, not on the spaces between the keys. 
6. The connect button looks like it has something to do with WiFi. A simple Login icon would work better IMO.
7. What do the Save and × Buttons do? And why is there a Spawn Ball button on the Settings page? Is in meant  as a simple test? Will it only work if I am connected?  
8. Is there a technical limitation to reading a QR code? It would be infinitely easier to just look at another device you opened HASS in.
9. If setting the protocol to WSS or WS is necessary, then make it impossible to do anything else. Make it a dropdown, or something.
10. I do not know if I should expect this to work if I am running Let's Encrypt and my UI is only accessible on HTTPS through DuckDNS. I don't expect you to write down the solution to every possible setup, but if it is known to be difficult/impossible/in any way different, do warn the user.
Should I use the IP? With ws or wss? Or the proper URL?
11. I could not answer the above question because it does not work with either. But more importantly it is inconsistent. If I try to connect through duckdns 10 times, 5 will say "Incorrect URL", and 5 will say "Invalid auth token".
12. To help with solving the previous problem, I would really, really like some more descriptive error messages. How is the URL invalid? It didn't find anything, or it found something that isn't HASS, or it deemed it unsafe to access? etc.

**Comment by Leblayd** [comment]
Oh, I think I found the issue. It was just the input field being terrible.

- The paste button does not _replace_ the contents, only appends to it. Which is fair, but there is no way to select text currently, and no "Clear" button, so clearing the field manually is a requirement.
- Scrolling left and right in it is really finicky, which is a big issue, as the token is very, very long, and the field is tiny.
- But you don't know when it's over, because when you remove the first shown character, it doesn't scroll the view to the left showing that there are still characters in there. You're fooled into thinking the field is now empty.
- The Backspace key cannot be held down, so you have to press it a ridiculous number of times, and the app lags each and every time you do.

Because of the above issues, and because I tried multiple times, with multiple keys, I now have to delete a few hundred characters. I am still in the process of doing it, because my fingers just got too tired.

**Comment by Nitwel** [comment]
Sorry for the inconvenience and thanks for all the feedback. You might be able to clear the apps data to reset the fields so you don't have to manually press the delete button 100 times.

I will look into improving the keyboard and documentation the coming days so hopefully the onboarding process should get a whole lot smoother soon.

**Comment by Nitwel** [comment]
I've tried to improve as much as feasible for now from your comments. It's part of the latest release. Here are some comments on things that can't be fixed for now:

> The instructions should be in the headset.

That will definitely come in a future update, but for now it's not a priority.

> If not in the headset, they should be under a large button on the website. Not an easy-to-miss link on the github page.

Will look into adding that soon, as it makes more sense than just having a Blog post on setup.

> Is there a technical limitation to reading a QR code?

I would love to implement something like it, but Meta doesn't give you access to any camera feed, so we have to wait until they implement an build in QR code scanner.

> I do not know if I should expect this to work if I am running Let's Encrypt and my UI is only accessible on HTTPS through DuckDNS

As long as it is the same URL as you use to open Home Assistant in the Browser (except for the ws/wss part) everything should be fine. If you only server over a secure connection, you have to use WSS.

Again, thanks for the feedback and don't hesitate to open another issue if you have more suggestions.

**Comment by Leblayd** [comment]
Absolutely understandable, thank you for the hard work!
It really is a shame about the QR, though :/

And yes, I can confirm it worked after all, the dns was no issue, it must have been the key's fault before.
Though I still have some pretty major issues with setting it up (too many to list), so I'll check the new release and follow the project for more
(And I hope I can contribute some code in the future, rather than just complaints)
