### ISSUE TITLE
Turn off boundary

### ISSUE THREAD

**Issue by markwarnants** [Nitwel/Immersive-Home#140]
I heard this might be constrained to certain developers, but if you can, it would be great to turn off the boundary for this, as it makes stairs very difficult, and boundaries can only be so big.

**Comment by Nitwel** [comment]
Right now you could build it from source and add an extra parameter to the AndroidManifest to disable boundaries in the app. https://docs.immersive-home.org/development/building.html

I should look into including that out of the box in the next GitHub release!

**Comment by Nitwel** [comment]
This can be closed as all releases on GitHub since version v0.6.1 should have the boundary disabled.
