### ISSUE TITLE
Can't delete buttons

### ISSUE THREAD

**Issue by markwarnants** [Nitwel/Immersive-Home#141]
Can you delete objects? It's not obvious.

**Comment by Nitwel** [comment]
When you grab a button, a trash bin should appear next to your left hand. I still have a minor bug in that you have to grab the button from the back for the trash bin to show up.

I should fix that and document entity creation and deletion. Thanks for the feedback!

**Comment by markwarnants** [comment]
Aaah cool - I missed that, but I have a load of Aqara devices, which have an "identify" entity. In your app they show up as buttons I think, just a square round words. I can't bin those, works with everything else I think.

Also, this is such a cool app - keep at it. Glad I just went straight for the app lab version, and paid!

**Comment by Nitwel** [comment]
Never seen those identify entities before and can't find much about them when searching. Should those be filtered out or do they have a purpose?

**Comment by markwarnants** [comment]
They don't seem to do anything lol... In HA they appear under diagnostic, so probably useless.
