### ISSUE TITLE
Names unclear

### ISSUE THREAD

**Issue by markwarnants** [Nitwel/Immersive-Home#142]
Can you use the device and entity "names" rather than their "IDs" from home assistant, as, at least in my home, the IDs are very non-descriptive, but the names are good.

**Comment by Nitwel** [comment]
For devices, I'm already doing that but you're right that not for entities. Will do that with the coming releases!

**Comment by markwarnants** [comment]
There is something funny going on here then, as all my Aqara wall switches are just called wall switch, even though in HA they all have descriptive names.
