### ISSUE TITLE
Room needs to be the same name?

### ISSUE THREAD

**Issue by markwarnants** [Nitwel/Immersive-Home#143]
I think this may be a documentation issue, but am I right in assuming the names of rooms in the app need to be the same as rooms in HA to get devices to add properly? Some devices were adding and some weren't, so I'm assuming I called the room something different. Also not sure if this app supports multi-story houses or not, but I have multi story rooms in HA.

**Comment by Nitwel** [comment]
Oh that's likely just a missleading error message from my part. I think I only alter the user that the entity is not in a room even though the message should state that said device isn't supported yet. 

The room system in Immersive Home is completely unrelated to the one in Home Assistant at the moment as I didn't want to mess up existing configurations and setups of people.
