### ISSUE TITLE
Home Assistant Freezes or Crashes and Restarts

### ISSUE THREAD

**Issue by Xllr8ing** [Nitwel/Immersive-Home#156]
Is this too system heavy for a raspberry pi 4 -8GB? After I connect after a couple moments, Home assistant freezes or restarts. I deleted my token and re-added and it still freezes or crashes and restart. I'd like to showcase this to my followers which may get you more traffic. 
Thanks in advance

**Comment by Nitwel** [comment]
A Pi 4 8GB should be more than enough to run home assistant on. Is the home assistant crashing in general or only when you open immersive home on your headset?

Also make sure that you are using the latest version of Home Assistant.

**Comment by Xllr8ing** [comment]
Thanks for the details, there is nothing in the instructions that mentions adding an add-on to Home Assistant  from https://docs.immersive-home.org/. If I missed that I should be adding from from HACs, please let me know.

**Comment by Nitwel** [comment]
All good, there is an Integration but it is optional. I'm currently in the process of releasing it to HACS. I also had some more thoughts on this and I'm pretty sure I used Immersive Home with a PI4 4GB earlier this year so it is very likely that there is something wrong with your installation of Home Assistant on that Pi and not necessarily with the app.

Let me know if you manage to connect it to a clean install of Home Assistant as except for looking at the logs, there isn't much on how I can help you with the given information.

**Comment by Nitwel** [comment]
@Xllr8ing did you have any success running it on a PI 5?

I bought a Pi5 too now and will try running HA with Immersive Home on it. If that works I would say we can close this issue as then it seems that the issue might be related to your home assistant installation or Pi4 and not the app.

**Comment by Nitwel** [comment]
I've installed Home Assistant on a Pi 5 4GB and connecting the app to it worked just fine. My guess is that either your Pi 4 or Home Assistant installation has a malfunction and that causes the crash.
I'll close this for now but if you can show that it is related to the app I'm happy to reopen this discussion.

**Comment by Xllr8ing** [comment]
Hello, so the issue wasn't the device after experimenting. The issue was
potentially software conflicts. I have another raspberry pi 4gb and it
worked flawlessly. There was no need to upgrade systems. I've been
experimenting with it and shared a few videos hoping to get everyone
intrigued about this project.
Few suggestions:  icons for on and off switches would be nice and access to
those upcoming sensors would also be good to have. I plan to install a
fresh copy of Home Assistant on my primary Pi as I'd like to gather
interest from my followers when they see the video I created that shows has
mileage hovering on top of my cars. I didn't quite seem to get any images
to show as of yet but this programing is absolutely amazing and I look
forward to sending more potential buyers your way.

Keep up the great work!

@Xllr8ing
