### ISSUE TITLE
Question about Removing Entities in Immersive Home for Meta Quest 3

### ISSUE THREAD

**Issue by zhouyoukang** [Nitwel/Immersive-Home#185]
I’ve successfully integrated Home Assistant with Meta Quest 3 using the Immersive Home project, and I’m really enjoying the experience so far! However, I’m encountering a problem when trying to delete entities (such as devices or panels) that I’ve previously added to the virtual environment.

I’ve tried various approaches, but I’m not sure how to properly remove them from the space. Could you please provide guidance on how to delete entities that have been placed in the virtual room?

Any help would be greatly appreciated!

Thanks in advance for your time and assistance!

**Comment by Nitwel** [comment]
Thank you very much! ❤️
You should be able to delete entities by grabbing them with the right hand and moving them into the trash bin that appears on your left hand when grabbing something. Hope that helped. 😄
