### ISSUE TITLE
Allow the tablet/menu to be grabbed and placed

### ISSUE THREAD

**Issue by MaxVRAM** [Nitwel/Immersive-Home#93]
Currently, the menu is fixed to the left controller/hand.

This could make using the interface challenging in some cases:

- Users who prefer using the opposite hand.
- Having to hold the hand still to read/interact with the menu.
- Entering text on the menu does not encourage left-hand interaction.

Allowing the user to grab and place the menu arbitrarily in the scene would solve these issues.

**Comment by Nitwel** [comment]
I started working on this in #83 by detaching the menu from any hand, so that should come with the next release. 😄

**Comment by MaxVRAM** [comment]
I just checked out the update and noticed the placeable panel. Nice work!
