### ISSUE TITLE
Immersive-Home can't connect homeassistant

### ISSUE THREAD

**Issue by klabc** [Nitwel/Immersive-Home#96]
I followed the guide at https://immersive-home.org/news/7. When I finished entering the URL 'ws://192.168.1.85:8123' and the token, I tried to click 'Connect', but I only received the message 'error code -1 invalid URL'. It is weird because I just tested my Home Assistant with the Chrome app: https://chromewebstore.google.com/detail/websocket-test-client/fgponpodhbmadfljofbimhhlengambbn.

**Comment by Nitwel** [comment]
Have you hosted Home Assistant with https? In that case you have to use `wss://` instead. Other than that, the url looks good to me.

**Comment by klabc** [comment]
Yes，I tried “wss” as well，but still got the error message.

**Comment by klabc** [comment]
I quit the app and then suddenly the URL blank showed the wrong word last night. I deleted them and everything worked. Actually, I had quit the app several times last night, but this time it worked
